config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :chapters
  resources :syllabuses
  resources :courses
  get 'user/index'
  get 'home/index'
  devise_for :users, :controllers => {:registrations => "registrations" } 
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController
  before_action :set_syllabus, only: [:show, :edit, :update, :destroy]

  def index
    @syllabuses = Syllabus.all
  end

  def show
  end

  def new
    @syllabus = Syllabus.new
  end

  def edit
  end

  def create
    @syllabus = Syllabus.new(syllabus_params)

    respond_to do |format|
      if @syllabus.save
        format.html { redirect_to @syllabus, notice: 'Syllabus was successfully created.' }
        format.json { render :show, status: :created, location: @syllabus }
      else
        format.html { render :new }
        format.json { render json: @syllabus.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @syllabus.update(syllabus_params)
        format.html { redirect_to @syllabus, notice: 'Syllabus was successfully updated.' }
        format.json { render :show, status: :ok, location: @syllabus }
      else
        format.html { render :edit }
        format.json { render json: @syllabus.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @syllabus.destroy
    respond_to do |format|
      format.html { redirect_to syllabuses_url, notice: 'Syllabus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syllabus
      @syllabus = Syllabus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syllabus_params
      params.require(:syllabus).permit(:name, :description, :duration)
    end
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/views/syllabuses/_form.html.erb
<%= simple_form_for(@syllabus) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :duration %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/syllabuses/edit.html.erb
<h1>Editing syllabus</h1>

<%= render 'form' %>

<%= link_to 'Show', @syllabus %> |
<%= link_to 'Back', syllabuses_path %>

app/views/syllabuses/index.html.erb
<h1>Syllabuses</h1>
<div class="course">
    <div class="table-responsive"> 
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Course Name</th>
                    <th>About the Course</th>
                    <th>Duration of Course (Hours)</th>
                    <th>Course Details</th>
                </tr>
            </thead>
            <tbody>
    <% @syllabuses.each do |syllabus| %>
      <tr>
        <td><%= syllabus.name %></td>
        <td><%= syllabus.description %></td>
        <td><%= syllabus.duration %></td>
        <td><%= link_to 'Show', syllabus, :class => 'btn btn-mini' %></td>
        <% if current_user.role == 'admin' %>
        <td><%= link_to 'Edit', edit_syllabus_path(syllabus), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', syllabus, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
        </table>
    </div>
</div>

<br>
<% if current_user.role == 'admin' %>
<%= link_to 'New Syllabus', new_syllabus_path, :class => 'btn btn-primary' %><br><br>
<%= link_to 'Back to Course', courses_path, :class => 'btn btn-primary' %>
<% end %>

app/views/syllabuses/new.html.erb
<h1>New syllabus</h1>

<%= render 'form' %>

<%= link_to 'Back', syllabuses_path %>

app/views/syllabuses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="course">
  <div class="table-responsive"> 
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Course Name</th>
          <th>About the Course</th>
          <th>Chapter Details</th>
        </tr>
      </thead>
      <tbody>
        <tr>
	        <td><%= @syllabus.name %></td>
	        <td><%= @syllabus.description %></td>
	        <td><%= link_to 'Chapter', chapter_path, :class => 'btn btn-mini' %></td>
	      </tr>
      </tbody>
    </table>
  </div>
</div>
<%= link_to 'Back to Course', courses_path, :class => 'btn btn-primary' %><br><br>
<% if current_user.role == 'admin' %>
<%= link_to 'Back to Syllabus', syllabuses_path, :class => 'btn btn-primary' %>
<% end %>