config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :chapters
  resources :syllabuses
  resources :courses
  get 'user/index'
  get 'home/index'
  devise_for :users, :controllers => {:registrations => "registrations" } 
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :duration)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for @course, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :duration %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                courses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Sl.No</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:duration) %> (in Hours)</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.id, course_path(course) %></td>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.duration %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      course_path(course), :class => 'btn btn-mini' %>
          <% if current_user.role == 'admin' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_course_path(course), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      course_path(course),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.role == 'admin' %>
<%= link_to "New Course", new_course_path, :class => 'btn btn-primary' %>
<% end %>

app/views/courses/new.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="course">
  <div class="table-responsive"> 
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Course Name</th>
          <th>About the Course</th>
          <th>Duration of Course (Hours)</th>
          <th>Syllabus Details</th>
        </tr>
      </thead>
      <tbody>
        <tr>
	        <td><%= @course.name %></td>
	        <td><%= @course.description %></td>
	        <td><%= @course.duration %></td>
	        <td><%= link_to 'Syllabus', syllabus_path, :class => 'btn btn-mini' %></td>
	      </tr>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Back to Course', courses_path, :class => 'btn btn-primary' %>