config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :chapters
  resources :syllabuses
  resources :courses
  get 'user/index'
  get 'home/index'
  devise_for :users, :controllers => {:registrations => "registrations" } 
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :syllabus
	belongs_to :course
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  def index
    @chapters = Chapter.all
  end

  def show
  end

  def new
    @chapter = Chapter.new
  end

  def edit
  end


  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:name, :description)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= simple_form_for(@chapter) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<h1 style="align:center">Chapters</h1>
<div class="course">
    <div class="table-responsive"> 
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Chapter Name</th>
                    <th>About the Chapter</th>
                    <th>Chapter Details</th>
                </tr>
            </thead>
            <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.name %></td>
        <td><%= chapter.description %></td>
        <td><%= link_to 'Show', chapter, :class => 'btn btn-mini' %></td>
        <% if current_user.role == 'admin' %>
        <td><%= link_to 'Edit', edit_chapter_path(chapter), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
        </table>
    </div>
</div>
<br>
<% if current_user.role == 'admin' %>
<%= link_to 'New Chapter', new_chapter_path, :class => 'btn btn-primary' %><br><br>
<%= link_to 'Back to Course', courses_path, :class => 'btn btn-primary' %>
<% end %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>
<div class="course">
  <div class="table-responsive"> 
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Chapter</th>
          <th>Chapter Details</th>
        </tr>
      </thead>
      <tbody>
        <tr>
	        <td><%= @chapter.name %></td>
	        <td><%= @chapter.description %></td>
	      </tr>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Back to Course', courses_path, :class => 'btn btn-primary' %><br><br>
<% if current_user.role == 'admin' %>
<%= link_to 'Back to Chapter', chapters_path, :class => 'btn btn-primary' %>
<% end %>